name: Doxygen GitHub Pages Deploy Action

on:
  push:
    branches:
      - main
    paths:
      - '**.h'
      - '**.c'
      - 'doc/Doxyfile'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate Doxygen documentation
        uses: mattnotmitt/doxygen-action@v1.9.8
        with:
          working-directory: doc/
          doxyfile-path: Doxyfile

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: doc/html/
